In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as mtp

In [2]:
data_set = pd.read_csv('C:/Users/smoha/OneDrive/ドキュメント/project/ml_project/StudentsPerformance.csv')

In [3]:
pd.DataFrame(data_set)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [4]:
data_set.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [5]:
data_set.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [6]:
data_set.nunique().sum

<bound method Series.sum of gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64>

In [7]:
data_set.isna().sum

<bound method DataFrame.sum of      gender  race/ethnicity  parental level of education  lunch  \
0     False           False                        False  False
1     False           False                        False  False
2     False           False                        False  False
3     False           False                        False  False
4     False           False                        False  False
..      ...             ...                          ...    ...
995   False           False                        False  False
996   False           False                        False  False
997   False           False                        False  False
998   False           False                        False  False
999   False           False                        False  False

     test preparation course  math score  reading score  writing score
0                      False       False          False          False
1                      False       False          False          False
2                      False       False          False          False
3                      False       False          False          False
4                      False       False          False          False
..                       ...         ...            ...            ...
995                    False       False          False          False
996                    False       False          False          False
997                    False       False          False          False
998                    False       False          False          False
999                    False       False          False          False

[1000 rows x 8 columns]>

In [8]:
print(data_set.nunique())

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
LabelEncoder_obj= LabelEncoder()
data_set['gender']=LabelEncoder_obj.fit_transform(data_set['gender'])
data_set['lunch']=LabelEncoder_obj.fit_transform(data_set['lunch'])
data_set['test preparation course']=LabelEncoder_obj.fit_transform(data_set['test preparation course'])

#one hot encoder
OneHotEncoder_obj=OneHotEncoder()
encoded_columns=OneHotEncoder_obj.fit_transform(data_set[['race/ethnicity','parental level of education']]).toarray()
encoded_df = pd.DataFrame(encoded_columns, columns=OneHotEncoder_obj.get_feature_names_out(['race/ethnicity', 'parental level of education']))
data_set1 = pd.concat([data_set, encoded_df], axis=1)
data_set1.drop(columns='parental level of education',inplace=True)
data_set1.drop(columns='race/ethnicity',inplace=True)

In [10]:
data_set1

,gender,lunch,test preparation course,math score,reading score,writing score,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,parental level of education_associate's degree,parental level of education_bachelor's degree,parental level of education_high school,parental level of education_master's degree,parental level of education_some college,parental level of education_some high school
0,0,1,1,72,72,74,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,0,1,0,69,90,88,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0,1,1,90,95,93,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,1,0,1,47,57,44,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1,1,1,76,78,75,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,1,0,88,99,95,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
996,1,0,1,62,55,55,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
997,0,0,0,59,71,65,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
998,0,1,0,68,78,77,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
999,0,0,1,77,86,86,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [11]:
data_set1.corr()['writing score'].sort_values(ascending=False)

writing score                                     1.000000
reading score                                     0.954598
math score                                        0.802642
lunch                                             0.245769
parental level of education_bachelor's degree     0.128297
parental level of education_master's degree       0.125693
race/ethnicity_group E                            0.089077
race/ethnicity_group D                            0.082032
parental level of education_associate's degree    0.064799
parental level of education_some college          0.027989
race/ethnicity_group C                           -0.010203
race/ethnicity_group B                           -0.078254
parental level of education_some high school     -0.097326
race/ethnicity_group A                           -0.110714
parental level of education_high school          -0.182211
gender                                           -0.301225
test preparation course                          -0.312946
Name: writing score, dtype: float64

In [12]:
data_set1.drop(columns='gender',inplace=True)
data_set1.drop(columns='test preparation course',inplace=True)
data_set1.drop(columns='race/ethnicity_group A',inplace=True)
data_set1.drop(columns='race/ethnicity_group B',inplace=True)
data_set1.drop(columns='race/ethnicity_group C',inplace=True)
data_set1.drop(columns='parental level of education_some high school',inplace=True)
data_set1.drop(columns='parental level of education_high school',inplace=True)
data_set1.drop(columns='parental level of education_some college',inplace=True)
data_set1

,lunch,math score,reading score,writing score,race/ethnicity_group D,race/ethnicity_group E,parental level of education_associate's degree,parental level of education_bachelor's degree,parental level of education_master's degree
0,1,72,72,74,0.0,0.0,0.0,1.0,0.0
1,1,69,90,88,0.0,0.0,0.0,0.0,0.0
2,1,90,95,93,0.0,0.0,0.0,0.0,1.0
3,0,47,57,44,0.0,0.0,1.0,0.0,0.0
4,1,76,78,75,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
995,1,88,99,95,0.0,1.0,0.0,0.0,1.0
996,0,62,55,55,0.0,0.0,0.0,0.0,0.0
997,0,59,71,65,0.0,0.0,0.0,0.0,0.0
998,1,68,78,77,1.0,0.0,0.0,0.0,0.0
999,0,77,86,86,1.0,0.0,0.0,0.0,0.0

In [13]:
from sklearn.preprocessing import StandardScaler
StandardScaler_obj=StandardScaler()
data_set2=StandardScaler_obj.fit_transform(data_set1)
data_set3=pd.DataFrame(data_set2)
data_set3

,0,1,2,3,4,5,6,7,8
0,0.741881,0.390024,0.193999,0.391492,-0.595830,-0.403473,-0.534179,2.733967,-0.250398
1,0.741881,0.192076,1.427476,1.313269,-0.595830,-0.403473,-0.534179,-0.365769,-0.250398
2,0.741881,1.577711,1.770109,1.642475,-0.595830,-0.403473,-0.534179,-0.365769,3.993639
3,-1.347925,-1.259543,-0.833899,-1.583744,-0.595830,-0.403473,1.872032,-0.365769,-0.250398
4,0.741881,0.653954,0.605158,0.457333,-0.595830,-0.403473,-0.534179,-0.365769,-0.250398
...,...,...,...,...,...,...,...,...,...
995,0.741881,1.445746,2.044215,1.774157,-0.595830,2.478479,-0.534179,-0.365769,3.993639
996,-1.347925,-0.269803,-0.970952,-0.859491,-0.595830,-0.403473,-0.534179,-0.365769,-0.250398
997,-1.347925,-0.467751,0.125472,-0.201079,-0.595830,-0.403473,-0.534179,-0.365769,-0.250398
998,0.741881,0.126093,0.605158,0.589015,1.678331,-0.403473,-0.534179,-0.365769,-0.250398
999,-1.347925,0.719937,1.153370,1.181586,1.678331,-0.403473,-0.534179,-0.365769,-0.250398

In [14]:
x = np.delete(data_set3, 3, axis=1) 
y = data_set3.iloc[:, 3]

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [16]:
from sklearn.linear_model import LinearRegression
LinearRegression_obj = LinearRegression()
LinearRegression_obj.fit(x_train,y_train)

LinearRegression()

In [17]:
from sklearn.metrics import r2_score
y_pred=LinearRegression_obj.predict(x_test)
r2=r2_score(y_test,y_pred)
print(f"r2 score:{r2:.4f}")

r2 score:0.9316

In [18]:
input=[[2,69,98,0.0,0.0,0.0,0.0,0.0]]  #input method =  lunch, math score, reading score, race/ethnicity_group D, race/ethnicity_group E, parental level of education_associate's degree, parental level of education_bachelor's degree, parental level of education_master's degree
from sklearn.pipeline import Pipeline
Pipeline_obj=Pipeline([
    ('scaler',StandardScaler_obj),
    ('prediction',LinearRegression_obj)
])
Pipeline_obj.fit(x_train,y_train)
predictions=Pipeline_obj.predict(input)
print('input',input)
print('input',predictions)

input [[2, 69, 98, 0.0, 0.0, 0.0, 0.0, 0.0]]
input [91.41193111]